.gitignore

Update gitignore for mac OS files

---

examples/accounts.json
examples/bulk_extractor_forensic_path.json
examples/file.json
examples/message.json
examples/multipart_file.json
examples/sms_and_contacts.json

References:
* [AC-165] Update style of relationship literals to UCO 0.4.0+ style
Signed-off-by: Alex Nelson <alexander.nelson@nist.gov>

Update style of relationship literals to UCO 0.4.0+ style

---

examples/illustrations/device/device.json

- Slight issue @ line 32 vs line 38 
Suggested change bios -> firmware doesn't seem like an accepted change? Have added but can resubmit without this change
@ajnelson-nist

Update to device.json

---

examples/illustrations/mobile_device_and_sim_card/mobile_device_and_sim_card.json

Update for AC-190

---

examples/illustrations/file/file.json

Update for AC-189

---

examples/illustrations/exif_data/exif_data.json

Update for AC-188

---

examples/illustrations/file/file.json

With the discussion on the Locations MVP proposal, there is now a way
forward for representing this desired association.
References:
* [ONT-186] (CP-30) Topic - Location

Address errant location association

---

examples/illustrations/Oresteia/Oresteia.json
examples/illustrations/accounts/accounts.json

References:
* [OC-153] UCO should clarify how to represent a person, versus(?) an
Identity
Signed-off-by: Alex Nelson <alexander.nelson@nist.gov>

Use more specific Person classes

---

examples/illustrations/call_log/call_log.json
examples/illustrations/call_log/call_log_validation.ttl

This patch series resolves most validation errors with the `call_log.json` example, to reduce the review complexity of [PR 36](https://github.com/casework/CASE-Examples/pull/36).

Update validation baseline for OC-195

---

examples/illustrations/call_log/call_log.json
examples/illustrations/call_log/call_log_validation.ttl

Addresses the proposed changes in CP-92 to demonstrate:
1. A basic two-way phone call between two parties with clear directionality.
2. A basic two-way phone call between two parties without clear directionality.
3. A three-way call with clear directionality between the caller and two recipients.
4. A conference bridge.

Update Cell Phone Use Cases

---

examples/illustrations/src/review.mk

This supports two active proposals.
References:
* [ONT-434] (CP-33) CASE needs to provide an inference object
* [ONT-469] (UCO CP-101) CASE needs a representation for a cellular
tower
Signed-off-by: Alex Nelson <alexander.nelson@nist.gov>

Incorporate drafting.ttl, if present

---

examples/illustrations/Oresteia/Oresteia.json
examples/illustrations/Oresteia/Oresteia_validation.ttl
examples/illustrations/mobile_device_and_sim_card/mobile_device_and_sim_card.json
examples/illustrations/mobile_device_and_sim_card/mobile_device_and_sim_card_validation.ttl

This will resolve [Issue 53](https://github.com/casework/CASE-Examples/issues/53).

Resolve type discrepancies with MSISDN

---

.gitmodules

This PR will also implement a (fortunately uneventful) test for [UCO PR 344](https://github.com/ucoProject/UCO/pull/344).

Use -Archives repositories instead of ajnelson-nist forks

---

examples/illustrations/.gitignore
examples/illustrations/Oresteia/Makefile
examples/illustrations/accounts/Makefile
examples/illustrations/bulk_extractor_forensic_path/Makefile
examples/illustrations/call_log/Makefile
examples/illustrations/device/Makefile
examples/illustrations/exif_data/Makefile
examples/illustrations/file/Makefile
examples/illustrations/forensic_lifecycle/Makefile
examples/illustrations/location/Makefile
examples/illustrations/message/Makefile
examples/illustrations/mobile_device_and_sim_card/Makefile
examples/illustrations/multipart_file/Makefile
examples/illustrations/network_connection/Makefile
examples/illustrations/raw_data/Makefile
examples/illustrations/reconstructed_file/Makefile
examples/illustrations/sms_and_contacts/Makefile
examples/illustrations/src/generic_snippet_combiner.py
examples/illustrations/src/illustration-basedir.mk
examples/illustrations/src/illustration-nosrc.mk
examples/illustrations/src/illustration-src.mk

This sets up Make patterns that will apply to several examples currently
under drafting that would also benefit from centralized validation.

Centralize Make recipes with include directive

---

examples/illustrations/Makefile
examples/illustrations/database_records/Makefile
examples/illustrations/database_records/README.md
examples/illustrations/database_records/database_records.json
examples/illustrations/database_records/database_records_validation-develop.ttl
examples/illustrations/database_records/database_records_validation-unstable.ttl
examples/illustrations/database_records/database_records_validation.ttl
examples/illustrations/database_records/drafting.ttl
examples/illustrations/database_records/src/Makefile
examples/illustrations/database_records/src/README.md.in
examples/illustrations/database_records/src/database_records-artifact_linking.json
examples/illustrations/database_records/src/database_records-file_location.json
examples/illustrations/database_records/src/database_records-file_with_meta.json
examples/illustrations/database_records/src/database_records-sqlite.json
examples/illustrations/database_records/src/database_records_base.json

Example usage for [UCO #415](https://github.com/ucoProject/UCO/issues/415)

UCO-415 Database Record Representation

---

examples/illustrations/configured_tool/configured_tool.json
examples/illustrations/configured_tool/configured_tool_validation-develop.ttl
examples/illustrations/configured_tool/configured_tool_validation-unstable.ttl
examples/illustrations/configured_tool/configured_tool_validation.ttl
examples/illustrations/configured_tool/drafting.ttl

This PR will increase validation errors for the configured tool example, but some of the errors are significantly unwieldy to mitigate without modification to the UCO Tool ontology.  The errors will appear reduced in an upcoming `unstable`-branch build.

Draft ConfiguredTool object

---

examples/illustrations/Oresteia/Oresteia.json
examples/illustrations/Oresteia/Oresteia_validation-develop.ttl
examples/illustrations/Oresteia/Oresteia_validation-unstable.ttl
examples/illustrations/Oresteia/Oresteia_validation.ttl
examples/illustrations/configured_tool/configured_tool.json
examples/illustrations/configured_tool/configured_tool_validation-develop.ttl
examples/illustrations/configured_tool/configured_tool_validation-unstable.ttl
examples/illustrations/configured_tool/configured_tool_validation.ttl
examples/illustrations/file/README.md
examples/illustrations/file/file.json
examples/illustrations/forensic_lifecycle/forensic_lifecycle.json
examples/illustrations/forensic_lifecycle/forensic_lifecycle_validation-develop.ttl
examples/illustrations/forensic_lifecycle/forensic_lifecycle_validation-unstable.ttl
examples/illustrations/forensic_lifecycle/forensic_lifecycle_validation.ttl
examples/illustrations/message/message.json
examples/illustrations/multipart_file/multipart_file.json
examples/illustrations/network_connection/network_connection.json
examples/illustrations/reconstructed_file/README.md
examples/illustrations/reconstructed_file/reconstructed_file.json
examples/illustrations/sms_and_contacts/sms_and_contacts.json

This pull request to update the following CASE examples in order that they are all lowercase, numeric idnetifiers are removed, and they all have a valid 16-byte UUID.
The nine (9) examples affected by this change are:
- configured_tool.json (44 changes);
- file.json (39 changes)*;
- forensic_lifecycle.json (252 changes);
- message.json (56 changes);
- multipart_file.json (23 changes);
- reconstructed_file.json (63 changes)*;
- sms_and_contacts.json (26 changes);
- network_connection.json (57 changes);
- Oresteia.json (237 changes);
Notes:
1. All the resultant changes were manually checked against their generated logs
2. Files marked with * also had changes made to their README.md files.
3. The readme file for reconstructed_file.json had a reference to forensic_action0, which is not in the …

Check & Update json example uuids (part 2 of 2)

---

examples/illustrations/spear_phishing/drafting.ttl
examples/illustrations/spear_phishing/spear_phishing-prov.ttl
examples/illustrations/spear_phishing/spear_phishing.json
examples/illustrations/spear_phishing/spear_phishing.ttl
examples/illustrations/spear_phishing/spear_phishing_validation-develop.ttl
examples/illustrations/spear_phishing/spear_phishing_validation-unstable.ttl
examples/illustrations/spear_phishing/spear_phishing_validation.ttl

Update spear phishing example

---

examples/illustrations/spear_phishing/spear_phishing_validation-develop.ttl
examples/illustrations/spear_phishing/spear_phishing_validation-unstable.ttl
examples/illustrations/spear_phishing/spear_phishing_validation.ttl
examples/illustrations/src/illustration-nosrc.mk

This is expected to have a long series of fixes done before CI passes.

Restrict validation results to Info-level

---

examples/illustrations/forensic_lifecycle/forensic_lifecycle.json

This is the second half of the change needed in 6e03b6e.

Implement and use initiation relationship

---

requirements.txt

No effects were observed on Make-managed files.

Bump case-utils

---

examples/illustrations/analysis/README.md
examples/illustrations/analysis/analysis.json
examples/illustrations/analysis/src/analysis-manual_malware.json
examples/illustrations/analysis/src/analysis-supplementary.json
examples/illustrations/configured_tool/configured_tool.json
examples/illustrations/database_records/README.md
examples/illustrations/database_records/database_records.json
examples/illustrations/database_records/src/database_records-file_with_meta.json
examples/illustrations/message/message.json
examples/illustrations/postvisit.mk
examples/illustrations/spear_phishing/spear_phishing.json
examples/illustrations/spear_phishing/spear_phishing.ttl
examples/illustrations/test_kb_case_examples_illustrations.py

This is part of implementing [CASE-Examples-QC PR 54](https://github.com/ajnelson-nist/CASE-Examples-QC/pull/54).

Test for IRIs that share UUIDs

---

examples/illustrations/existence_intervals/existence_intervals.json
examples/illustrations/existence_intervals/src/existence_intervals-time.json

Review shapes are left for a separate patch series.

Add existence intervals instance data for external-to-UCO ontologies
